import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignIn,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import SignComponent from "@/components/core/SignComponent";
import NavigationBaby from "@/components/core/NavigationBaby";
import UserNavigation from "@/components/core/UserNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className="  font-Liter">
          <SignedOut>
            <div className=" relative min-h-screen">
              <div className=" absolute pointer-events-none top-0 left-0 w-full h-full backdrop-blur-[2px] z-10 bg-background/10"></div>
              <div className=" absolute overflow-hidden    top-0 left-0  h-full w-full z-0 ">
                <div className=" bg-gradient-to-t pointer-events-none from-transparent to-background w-full h-1/3 top-0 left-0 absolute " />
                <img src="artboard.svg" alt="" />
              </div>
              <NavigationBaby />
              <div className=" relative z-30 pt-14">
                <SignComponent />
              </div>
            </div>
          </SignedOut>

          {/* for signed in fillas  */}
          <SignedIn>
            <UserNavigation />
            <main className=" pt-24">{children}</main>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
